version: "3"
services:
  backend:
    image: mage-spring-boot
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8082:8082"
    volumes:
      - ./:/usr/src/app
    command: tail -F /dev/null
